spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: kalia
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update
